### ISSUE TITLE
Bad image upload

### ISSUE THREAD

**Issue by csabi23** [McoreD/TDMaker#11]
when i upload lots of picture the program not upload fine.
[TDMaker-20151231-debug.txt](https://github.com/McoreD/TDMaker/files/75884/TDMaker-20151231-debug.txt)
[TDMaker-20160101-debug.txt](https://github.com/McoreD/TDMaker/files/75885/TDMaker-20160101-debug.txt)
Thank you for your help.

**Comment by McoreD** [comment]
https://translate.google.com/#auto/en/Nem%20%C3%ADrhat%C3%B3%20adat%20a%20sz%C3%A1ll%C3%ADt%C3%A1si%20kapcsolatra%3A%20A%20l%C3%A9tez%C5%91%20kapcsolatot%20a%20t%C3%A1voli%20%C3%A1llom%C3%A1s%20k%C3%A9nyszer%C3%ADtetten%20bez%C3%A1rta suggests a host error. Unfortunately this is not an error within TDMaker. Sorry for the delayed response.
