### ISSUE TITLE
TDmaker question. How do I change the default piece size from 256kb to something larger

### ISSUE THREAD

**Issue by nickodemos** [McoreD/TDMaker#14]
TDmaker question. How do I change the default piece size from 256kb to something larger

**Comment by flyingpianoman** [comment]
Fixed once https://github.com/McoreD/TDMaker/pull/15 gets merged

**Comment by McoreD** [comment]
Please see https://github.com/McoreD/TDMaker/releases
Thanks @flyingpianoman
